---
stages:
  - static

style:
  stage: static
  tags:
    - bash
  image: $WY_REGISTRY/library/python:3.6-alpine3.7
  before_script:
    - pip install -c requirements-dev.txt unify yapf
  script:
    - unify -r -c setup.py genbox_cli
    - yapf -r -d setup.py genbox_cli

pyflakes:
  stage: static
  tags:
    - bash
  image: $WY_REGISTRY/library/python:3.6-alpine3.7
  before_script:
    - pip install -c requirements-dev.txt pyflakes
  script:
    - pyflakes setup.py genbox_cli

pylint:
  stage: static
  tags:
    - bash
  image: $WY_REGISTRY/library/python:3.6-alpine3.7
  before_script:
    - pip install -r requirements.txt
    - pip install -c requirements-dev.txt pylint
  script:
    - pylint setup.py genbox_cli
