.python-template: &python
  stage: static
  except:
    - tags
  tags:
    - bash
  image: $WY_REGISTRY/library/python:3.6.8-alpine-3.9

stages:
  - static
  - build

style:
  <<: *python
  before_script:
    - pip install -c requirements-dev.txt unify yapf
  script:
    - unify -r -c setup.py genbox_cli
    - yapf -r -d setup.py genbox_cli

pyflakes:
  <<: *python
  before_script:
    - pip install -c requirements-dev.txt pyflakes
  script:
    - pyflakes setup.py genbox_cli

pylint:
  <<: *python
  before_script:
    - apk add gcc musl-dev
    - pip install -r requirements.txt
    - pip install -c requirements-dev.txt pylint
  script:
    - pylint setup.py genbox_cli

create deb package:
  stage: build
  only:
    - tags
  tags:
    - docker-build
  image: ubuntu:18.10
  variables:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  before_script:
    - apt update
    - apt upgrade -y
    - apt install -y python3-setuptools python-all python3-all python3-pip debhelper
    - pip3 install pipenv
  script:
    - pipenv install --dev
    - make deb
  artifacts:
    name: ${CI_JOB_STAGE}-${CI_PROJECT_NAME}-${CI_COMMIT_TAG}
    paths:
      - deb_dist/
      - genbox-cli-${CI_COMMIT_TAG}.tar.gz
