.python-template: &python
  stage: static
  tags:
    - bash
  image: $WY_REGISTRY/library/python:3.6.8-alpine-3.9

stages:
  - static

style:
  <<: *python
  before_script:
    - pip install -c requirements-dev.txt unify yapf
  script:
    - unify -r -c setup.py genbox_cli
    - yapf -r -d setup.py genbox_cli

pyflakes:
  <<: *python
  before_script:
    - pip install -c requirements-dev.txt pyflakes
  script:
    - pyflakes setup.py genbox_cli

pylint:
  <<: *python
  before_script:
    - apk add gcc musl-dev
    - pip install -r requirements.txt
    - pip install -c requirements-dev.txt pylint
  script:
    - pylint setup.py genbox_cli

